### ISSUE TITLE
Freezes and consumes all available memory

### ISSUE THREAD

**Issue by mandrav** [TheNEStOnline/Multi-Extrusion-post-processing-scripts-for-Slic3r#4]
Hi,

nice work with this script. I haven't tested it yet though because it eats all 16G of memory I have and then some!

I tried debugging it and concluded that the problem appears when extrusion width is set as 0 (auto). The code seems to be using this value verbatim (as 0), leading to subsequent infinite loop somewhere (sorry, no perl guru here to dive deeper).

For the time being, I have changed my extrusion width to another value (not 0) and the problem appears to have been fixed. It 'd be nice of you though to correct for this case in code :)

**Comment by TheNEStOnline** [comment]
I think I have fixed that issue now.
It actually used nozzle diameter instead of extrusion width but that is changed now.

**Comment by TheNEStOnline** [comment]
Please retest if ok I can close this one and thanks for the support.

**Comment by TheNEStOnline** [comment]
Ditten mean to close it...

**Comment by mandrav** [comment]
Tested and working fine.
Thanks for the quick fix!
